### ISSUE TITLE
Change Ruler background color

### ISSUE THREAD

**Issue by MTayyabSarfraz** [elsunhoty/Ruler-picker#1]
hi, @elsunhoty I'm unable to change the background color of the ruler view,
this is a small property with an enormous impact.
I would love to hear about that if it is already there but I'm missing 
else will try to add this functionality by myself and let you know :)

**Comment by MTayyabSarfraz** [comment]
Sorry! 
Later realized it is already there attributed with the property **_`ruler_long_hash_mark_text_color`_**

**Comment by elsunhoty** [comment]
@MTayyabSarfraz  you are welcome to contribute
